pi@gopigo1:~/projet-2IN013 $ python3 mainIRL.py >> error.txt
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x73b0ed00 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
2
150
Traceback (most recent call last):
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pi/projet-2IN013/mainIRL.py", line 51, in <module>
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    menu()
  File "/home/pi/projet-2IN013/mainIRL.py", line 43, in menu
  File "/usr/lib/python3.9/threading.py", line 892, in run
    controleur.lancerStrategie(mur)
  File "/home/pi/projet-2IN013/src/controleur/controleur.py", line 44, in lancerStrategie
    self._target(*self._args, **self._kwargs)
    self.strat_en_cour.start()
  File "/home/pi/projet-2IN013/src/controleur/strategies.py", line 102, in start
  File "/home/pi/projet-2IN013/src/controleur/controleur.py", line 28, in mainControleur
    self.distrob = self.robA.getDistanceA()
  File "/home/pi/projet-2IN013/src/robots/gopigo.py", line 63, in getDistanceA
    self.strat_en_cour.step()
    return self.robot.get_distance()
    
  File "/home/pi/git/2IN013robot2022/src/robot2IN013/robot2IN013.py", line 110, in get_distance
  File "/home/pi/projet-2IN013/src/controleur/strategies.py", line 111, in step
    return self.distanceSensor.read_range_single(False)
  File "/usr/local/lib/python3.9/dist-packages/di_sensors/distance_sensor.py", line 80, in read_range_single
    self.distrob = self.robA.getDistanceA()
    value = self.VL53L0X.read_range_single_millimeters()
  File "/usr/local/lib/python3.9/dist-packages/di_sensors/VL53L0X.py", line 860, in read_range_single_millimeters
  File "/home/pi/projet-2IN013/src/robots/gopigo.py", line 63, in getDistanceA
    self.i2c_bus.write_reg_8(0x80, 0x01)
  File "/usr/local/lib/python3.9/dist-packages/di_i2c.py", line 228, in write_reg_8
    return self.robot.get_distance()
    self.transfer([reg, val])
  File "/usr/local/lib/python3.9/dist-packages/di_i2c.py", line 193, in transfer
  File "/home/pi/git/2IN013robot2022/src/robot2IN013/robot2IN013.py", line 110, in get_distance
    return_val = self.i2c_bus.transfer(self.address, outArr, inBytes)
  File "/usr/local/lib/python3.9/dist-packages/di_i2c.py", line 477, in transfer
    return self.distanceSensor.read_range_single(False)
  File "/usr/local/lib/python3.9/dist-packages/di_sensors/distance_sensor.py", line 80, in read_range_single
    raise IOError("[Errno 5] Input/output error")
OSError: [Errno 5] Input/output error
    value = self.VL53L0X.read_range_single_millimeters()
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x2135778)

Current thread 0x76f00980 (most recent call first):
<no Python frame>
Aborted

